### ISSUE TITLE
Size Mismatch !

### ISSUE THREAD

**Issue by masta28** [goeo-/pythech-repo#3]
Hi Goeo , I've tried your password protected repo script , everything works fine except when user trying to install the deb file , Cydia gives error message Size Mismatch . If possible can you fix that issue please  ?

**Comment by Spydar007** [comment]
That will be to do with the content of your deb file, not the repo or errrr.

**Comment by masta28** [comment]
I don't think it's about the content of the deb file , If I don't use htaccess or change rewrite rule from request deb to something else I can install deb file without signing in ....

**Comment by goeo-** [comment]
are you sure you have the latest version of errrr? is the deb accessible by the user running php?

**Comment by masta28** [comment]
Hi Goeo , thanks for replying , Yes I am sure I have the latest errrr. 
[1](https://cloud.githubusercontent.com/assets/5741631/8605216/aa70b330-267b-11e5-92c3-240d961f5100.PNG)
As you can see from the picture above , cydia always says Size Mismatch ( This is user after signing in and then try to install , without signing in user gets error 403 )
[2](https://cloud.githubusercontent.com/assets/5741631/8605361/b47c237c-267c-11e5-9a51-e63e008a0d88.PNG)
Second picture is taken after I changed htaccess , I've changed - 
RewriteRule ^.+.deb$ main.php?request=%{REQUEST_FILENAME}  to
RewriteRule debs/^.+.deb$ main.php?request=%{REQUEST_FILENAME}
and then user can install deb file without signing in 

(edited to unembed images. new iphones are way too big.)

**Comment by goeo-** [comment]
`debs/^.+.deb$` is an invalid regex. you're not using errr right now, you're using direct connections: everybody can download. can you `ls -la` in the directory and send me that? maybe it's a permissions issue?

**Comment by masta28** [comment]
Here you go , this is the result of ls -la  in main directory ...
drwxr-xr-x  13 masta  staff   442 10 Jul 16:56 .
drwx------+ 14 masta  staff   476 10 Jul 00:06 ..
-rw-r--r--@  1 masta  staff   115  9 Jul 21:30 .htaccess
-rw-r--r--   1 masta  staff   475  9 Jul 21:43 Packages
-rw-r--r--   1 masta  staff   376  9 Jul 21:43 Packages.bz2
-rw-r--r--   1 masta  staff   371  9 Jul 21:43 Packages.gz
-rw-r--r--@  1 masta  staff   233  8 Jul 22:08 Release
-rw-r--r--   1 masta  staff   322  8 Jul 22:20 auth.php
-rw-r--r--   1 masta  staff   971  8 Jul 22:20 config.php
-rw-r--r--   1 masta  staff   180  8 Jul 22:20 connect.php
drwxr-xr-x   3 masta staff   102 10 Jul 16:56 debs
-rw-r--r--@  1 masta  staff  4300  8 Jul 22:24 depiction.php
-rw-r--r--@  1 masta  staff  1572  9 Jul 21:33 main.php

**Comment by goeo-** [comment]
very weird. i see that you don't have an `auth` directory. but that would normally cause a `403 Not Authenticated` (since `./auth/$ip` can never exist, see https://github.com/goeo-/errrr/blob/master/main.php#L51) not a Size Mismatch. have you modified errrr at all?

**Comment by masta28** [comment]
No I didn't modify anything .  I've auth directory , it's in the server , forgot to create one in local directory..
Yes you are right , without auth directory it'll give error...

**Comment by goeo-** [comment]
i asked for a ls -la from where this error happens

**Comment by masta28** [comment]
This is the result ( htaccess file hidden in the picture , but it exist ) 

drwxr-xr-x  auth
-rw-r--r-- .htaccess
-rw-r--r--  Packages
-rw-r--r-- Packages.bz2
-rw-r--r--  Packages.gz
-rw-r--r-- Release
-rw-r--r--  auth.php
-rw-r--r--  config.php
-rw-r--r--  connect.php
drwxr-xr-x  debs
-rw-r--r-- depiction.php
-rw-r--r-- main.php

![list](https://cloud.githubusercontent.com/assets/5741631/8630792/2ee5ec2a-2762-11e5-923b-d2c2c6c06ece.png)

**Comment by masta28** [comment]
Problem has been solved . 
switch($uniquepackages){
		case TRUE:
			echo  readfile("$request.".file_get_contents("auth/$ip"));
			break;
		default:
		case FALSE:
		   echo readfile($request);
			break;
	}
	unlink("auth/$ip");

It's not  echo readfile($request) , actually readfile ($request) . just remove echo from the line , it's working perfectly .

**Comment by goeo-** [comment]
this is very weird. i just read the php documentation and you seem to be right. i wonder why this was working for everyone else (including myself), though. what php version are you on?

**Comment by masta28** [comment]
I've solved problem ,

**Comment by masta28** [comment]
I am testing my cydia repo now , just want to make sure everything works fine ..
Actually I wrote how to fix it , but suddenly my repo has given me same problem that's why I deleted last comment

**Comment by masta28** [comment]
Look like everything works fine , here is the problem why cydia gives size mismatch .
on the main.php script actually it's not [ echo readfile($request) ]  we have to remove [ echo ] from the line so it will be  [ readfile($request) ] ... 
after removing echo from the line works perfectly ....

**Comment by masta28** [comment]
I'm using php version 5.3 , maybe that's why I receive size mismatch problem , I've tested your new changes on the main.php , now it gives 500 internal server error . 
In my case if I remove echo from the main.php , it'll work fine ...
